config/routes.rb
SmMedokoroServer::Application.routes.draw do
  root :to => "home#index"

  get 'today' => 'home#today_movies'

  resources :movies, only: [:show]

  get 'random' => 'movies#random', as: :random

  get ':year/:month/:day' => 'movies#date_order', as: :date

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessor :name
  belongs_to :movie
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :categories
  validates :title, :provider, :url, presence: true
  validates :url, specific_url: true

  scope :youtube, -> { where(provider: 'youtube') }
  scope :niconico, -> { where(provider: 'niconico') }
  scope :vimeo, -> { where(provider: 'vimeo') }
  scope :fc2, -> { where(provider: 'fc2') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :allow_cross_domain_access
  def allow_cross_domain_access
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    response.headers["Access-Control-Allow-Methods"] = "GET"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    start_date = Date.yesterday + 9.hours
    end_date   = start_date + 1.day
    @movies    = Movie.where(created_at: start_date..end_date).order('created_at DESC')
    respond_to do |format|
      if @movies.empty?
        format.html {render template: 'errors/empty'}
      else
        format.html
      end
      format.json{render json: @movies}
    end
  end

  def today_movies
    start_date = Date.yesterday + 9.hours
    end_date   = start_date + 1.day
    @today_movies = Movie.where(created_at: start_date..end_date).order('created_at DESC')
    respond_to do |format|
      format.json{render json: @today_movies}
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :validate_date, only: :date_order

  def show
    @movie = Movie.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @movie}
    end
  end

  def random
    @movie = Movie.first(offset: rand(Movie.count) )
    respond_to do |format|
      format.html {render :show, notice: "ランダム再生で移動されました"}
      format.json {render json: @movie, action: :show}
    end
  end

  def date_order
    start_date = @params_date.yesterday + 9.hour
    end_date = start_date + 1.day
    @movies = Movie.where(created_at: start_date..end_date).order("created_at DESC")

    respond_to do |format|
      if @movies.empty?
        format.html {render template: 'errors/empty'}
      else
        format.html
      end
      format.json {render json: @movies}
    end
  end

  private
  def validate_date
    begin
      @params_date = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
      #未来の日付のとき
      if @params_date > Date.today
        render 'errors/future_date.html', status: 404
      end
    rescue
      #日付として存在しないとき
      render 'errors/not_exist_date.html', status: 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def search_date
    if Date.valid_date?(params[:year].to_i, params[:month].to_i, params[:day].to_i)
      Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
    else
      Date.today
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/index.html.erb
<%= render partial: "layouts/movie_list", locals: { movies: @movies } %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header pull-left">
       <a class="navbar-brand" href="<%= root_path %>">デイリー人気動画</a>
    </div>

    <div class="navbar-header pull-right">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" id="show-date">
            <span class="year"><%= search_date.year %></span>年
            <span class="month"><%= search_date.month %></span>月
            <span class="day"><%= search_date.day %></span>日 <span class="caret"></span>
          </a>
        <%# TODO: 日付のリストの表示%>
          <ul class="dropdown-menu date-list" role="menu" aria-labelledby="dLabel">
            <% (Movie.first.created_at.to_date..Date.today).reverse_each do |date| %>
              <li class="date <%= 'active' if date == search_date %>">
                <%=link_to date_path(date.year, date.month, date.day) do %>
                  <span class="date year" style="font-size:18px;"><%= date.year %></span>年
                  <span class="date month" style="font-size:18px;"><%= date.month %></span>月
                  <span class="date day" style="font-size:18px;"><%= date.day %></span>日
                <% end %>
              </li>
            <% end %>
         </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li>
          <%=link_to "ALL", "#all", class: "filter", data: {filter: 'all'} %>
        </li>
        <li>
          <%=link_to "おまかせ", random_path %>
        </li>
        <li>
          <%=link_to "Youtube", "#youtube", class: "filter", data: {filter: 'youtube'} %>
        </li>
        <li>
          <%=link_to "ニコニコ動画", "#niconico", class: "filter", data: {filter: "niconico"} %>
        </li>
        <li>
          <%=link_to "Vimeo", "#vimeo", class: "filter", data: {filter: "vimeo"} %>
        </li>
        <li>
          <%=link_to "FC2", "#fc2", class: "filter", data: {filter: "fc2"} %>
        </li>
      </ul>
    </div><!--/.nav-collapse-->
  </div>
</div>

app/views/layouts/_movie_list.html.erb
<ul class="row" id="movies">
	<% movies.each do |movie| %>
		<li class="col-md-3 movie-list mix mix_all <%= movie.provider %>">
			<%=link_to(movie_path(movie.id)) do %>
				<div class="data">
					<%= image_tag movie.thumbnail,{ class: "img-responsive movie-img"} %>
					<div class="detail-box">
						<div class="title">
							<p><%= movie.title%></p>
						</div>
					</div>
				</div>
			<% end %>
		</li>
	<% end %>
</ul>
<%# TODO: linkにホバーしたときの下線は消す %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "デイリー人気動画"%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render partial: "layouts/header" %>
	<div class="container" id="movies-container">
		<%= yield %>
	</div>
</body>
</html>

app/views/movies/date_order.html.erb
<% content_for :title do %>
	<%= params[:year] %>/
	<%= params[:month] %>/
	<%= params[:day] %>の動画サイトで人気の動画
<% end %>

<%= render partial: "layouts/movie_list", locals: {movies: @movies} %>

app/views/movies/provider_order.html.erb
<% content_for :title do %>
	<%=	params[:provider].to_s.capitalize %>で人気の動画
<% end %>

<ul class="row movies">
	<% @movies.each do |movie| %>
		<%= render partial: "layouts/movie_list", locals: {movie: movie} %>
	<% end %>
</ul>

app/views/movies/show.html.erb
<div id="info">
	<%=image_tag @movie.thumbnail %>
	<span><%= @movie.title %></span>
	<div><%=link_to "#{@movie.provider.capitalize}で見る", @movie.url %> </div>
</div>

<div id="player">
	<% case @movie.provider %>
	<% when "youtube" %>
		<iframe width="700" height="394" src="//www.youtube.com/embed/<%= @movie.videoid %>" frameborder="0" allowfullscreen></iframe>
	<% when "niconico" %>
		<script type="text/javascript" src="http://ext.nicovideo.jp/thumb_watch/<%= @movie.videoid %>?w=700&h=394"></script>
	<% when "vimeo" %>
		<iframe src="//player.vimeo.com/video/<%= @movie.videoid %>" width="700" height="394" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
	<% when "fc2" %>
		<script src="http://static.fc2.com/video/js/outerplayer.min.js" url="http://video.fc2.com/ja/content/<%=@movie.videoid%>/" tk="" tl="<%= @movie.title %>" sj="31000" d="" w="700" h="394" charset="UTF-8"></script>
		<script type="text/javascript">
			$(function() {
				$(window).load(function(){
					$("#player div").css({"max-width":"100%", "height":"auto !important"})
				});
			});
		</script>
	<% else %>
		Sorry, This video is not supported.
	<% end %>
</div>